### ISSUE TITLE
EnforceConsumerDeletion flag on DeleteStream not processed properly

### ISSUE THREAD

**Issue by whummer** [etspaceman/kinesis-mock#120]
If `EnforceConsumerDeletion=true` is passed on `DeleteStream`, the system should delete any existing stream consumer entities.

Instead, it seems that kinesis-mock raises an exception if `EnforceConsumerDeletion` is set and consumers are present:
https://github.com/etspaceman/kinesis-mock/blob/b0b432de2052cf6b81fb5d04426851998f9aeb38/src/main/scala/kinesis/mock/api/DeleteStreamRequest.scala#L29-L35

@etspaceman Please let me know if we can help out with this change. Thanks!

**Comment by etspaceman** [comment]
Ah it seems I have the logic backwards. This should only be raised if the value is unset or false. I can make a change to fix. Thanks for the report.

**Comment by etspaceman** [comment]
Closed w/ #121

**Comment by whummer** [comment]
Thanks! 👍 
/cc @thrau

**Comment by etspaceman** [comment]
0.1.1 will be published with artifacts shortly with this change @whummer
