### ISSUE TITLE
PutRecordsResponse records in wrong order?

### ISSUE THREAD

**Issue by svroonland** [etspaceman/kinesis-mock#148]
I have a unit test that checks that the shard IDs as returned by PutRecords are as predicted. Since localstack 0.12.13 this test is failing.  The correct shard IDs are in the response, just in a different order. Is it possible that the order of the records in PutRecordsResponse is incorrect w.r.t. the requests?

**Comment by etspaceman** [comment]
Can you provide an example request and response vs what you're looking for?

**Comment by svroonland** [comment]
Maybe I can clarify a bit with an example.

Say I have a stream with 5 shards and I'm making a `PutRecords` request with some records with keys `key1`, `key2`, `key3`. Based on the partition keys, these records would end up (hypothetically) on shards 2, 3 and 5. I have a function in my unit test that calculates the expected shard, (reverse-engineered from the AWS Kinesis Producer Library).

When I get back the `PutRecordsResponse` from kinesis-mock, I look at the `shardId` property of each `PutRecordsResultEntry`. I expect it to be `[2, 3, 5]` in order, but instead I get something like `[5, 2, 2]`, i.e. a random order. So the correct shard IDs are in the result list, just not in the right order.

I would expect each result entry in `PutRecordsResponse` to correspond to the entries in the `PutRecordsRequest` in order. At least that is what AWS does and what `kinesalite` does. 

Hope that helps to clarify :)

**Comment by etspaceman** [comment]
I've got a PR to solve this and added a test for it. I'll release a new version for you to test soon (you can do this via Localstack by passing in a `KINESIS_MOCK_VERSION` environment variable)

**Comment by etspaceman** [comment]
@svroonland Release is building now. Should be ready in about 30 minutes. When it is ready, can you try with `KINESIS_MOCK_VERSION=0.1.5`?

**Comment by svroonland** [comment]
Thanks for the quick response.

The test is still failing unfortunately. I think the env var is not being picked up, because I see no errors in the localstack logs when I run with 0.1.9 or some other non-existent version. I'm using docker-compose like so:

```
version: '3'

services:
  localstack:
    image: localstack/localstack:0.12.15
    healthcheck:
      test: ["CMD-SHELL", "awslocal kinesis list-streams"]
      interval: 5s
      timeout: 2s
      retries: 10
    environment:
      LOCALSTACK_HOST: localstack
      SERVICES: 'kinesis,cloudwatch,dynamodb'
      USE_SSL: "false"
      DEFAULT_REGION: 'us-east-1'
      AWS_DEFAULT_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: dummy-key
      AWS_SECRET_ACCESS_KEY: dummy-key
      KINESIS_MOCK_VERSION: 0.1.9
      DEBUG: "1"
    ports:
      - "4566:4566"
```

**Comment by etspaceman** [comment]
Hmm, that is odd. @whummer is this the correct use of that environment variable?

**Comment by etspaceman** [comment]
@svroonland Can you try testing using the kinesis-mock image directly? You can see an example docker-compose setup here: https://github.com/etspaceman/kinesis-mock/blob/main/docker/docker-compose.yml

**Comment by etspaceman** [comment]
@whummer any thoughts on the environment variable usage?

**Comment by svroonland** [comment]
Just tried, but same issue unfortunately..

**Comment by etspaceman** [comment]
Thinking more about this, shouldn't the returned records in a PutRecordsResponse match the order that they were submitted in PutRecordsRequest? That is a pretty important detail for retrying failed records, as you can only match up the failed record to the request via the index of the array.

**Comment by svroonland** [comment]
Yeah that's the idea :)

**Comment by etspaceman** [comment]
I don't see anything obvious in the code that would be putting these records out of order but I can take a closer look when I get a chance.

**Comment by etspaceman** [comment]
Hmm, actually I think I see a cause. Ill see if I can put out a change here in a while.

**Comment by svroonland** [comment]
I'd be happy to review it (scala dev as well, working on https://github.com/svroonland/zio-kinesis)

**Comment by etspaceman** [comment]
Cool, thanks. I think this is the offending line:

https://github.com/etspaceman/kinesis-mock/blob/main/src/main/scala/kinesis/mock/api/PutRecordsRequest.scala#L58

It puts the records into a Map which doesn't retain the input ordering.

**Comment by svroonland** [comment]
That line caught my eye earlier, but I wasn't sure. Seems likely.

**Comment by etspaceman** [comment]
Made a PR if you want to put some eyes on it @svroonland: #151

**Comment by svroonland** [comment]
Seems good to me!

**Comment by svroonland** [comment]
Works perfectly now, thanks so much!

**Comment by etspaceman** [comment]
Glad to hear it! Thanks for opening the bug report and working with me on a resolution.
