### ISSUE TITLE
Multi Region Support needed.

### ISSUE THREAD

**Issue by pinzon** [etspaceman/kinesis-mock#185]
Hi I'm currently trying to fix this issue (localstack/localstack#4522) but seems to me that the problem originates in this project due to the lack of support for MultiRegion.

# Steps to reproduce 
```sh
AWS_DEFAULT_REGION=us-east-2 aws --endpoint-url http://localhost:4566 kinesis create-stream --stream-name kinesisStream --shard-count 1
AWS_DEFAULT_REGION=us-east-2 aws --endpoint-url http://localhost:4566 kinesis describe-stream --stream-name kinesisStream | jq .StreamDescription.StreamAR
```
# Expected Result 
`arn:aws:kinesis:us-east-2:074255357339:stream/kinesisStream`

# Actual Result
`"arn:aws:kinesis:us-east-1:000000000000:stream/kinesisStream"`

I understand that there's a variable for setting the default region but the region could also be taken from the Authrization Header of the createStreamRequest to see the current default region of the client.

Also I tried to fix it myself but I really have a hard time trying to understand functional programming code 😅

Thanks for any help you could provide.

**Comment by etspaceman** [comment]
Thanks for the report! I'll take a look into this.

**Comment by etspaceman** [comment]
So I've been poking around at this implementation and it will be a fairly significant overhaul. The current in-memory model only expects data for a single region, so storing data for multiple regions will be a complicated task. I'm not sure it will be a short turnaround time, but I will keep you informed of the updates.

Something I'll note is that I don't believe that this was supported in Kinesalite (correct me if I'm wrong @whummer), so I don't think its a _regression_ with that in mind. We're looking at this as a feature-add, yes?

**Comment by etspaceman** [comment]
I was able to get this going in #187

**Comment by pinzon** [comment]
@etspaceman Thank you so much!!!
