### ISSUE TITLE
[BUG] Authentication expects a space after commas in Authorization header parameters

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [etspaceman/kinesis-mock#387]
**Describe the bug**

[LocalStack](https://github.com/localstack/localstack), which uses, in its Docker container, `kinesis-mock` is reporting to my Elixir [`ex_aws`](https://github.com/ex-aws/ex_aws) -based application that "Authorization header requires \\Signature\\ parameter. Authorization header requires \\SignedHeaders\\ parameter." ([linked Localstack issue](https://github.com/localstack/localstack/issues/7358))

It seems parsing expects a space between `,` and the next parameter when this is not required by AWS.

**To Reproduce**

1. run `java -jar ./kinesis-mock.jar` (exposed 4568 for plain HTTP requests)
2. `curl -v -X POST -H "Authorization: AWS4-HMAC-SHA256 Credential=test/20221219/us-east-1/kinesis/aws4_request,SignedHeaders=content-type;host;x-amz-date;x-amz-target,Signature=ba9705e002b4f224d08c908606f0076a7f4f53bcc68315897764c587c7e5ffb5" -H "content-type: application/x-amz-json-1.1" -H "host: localhost:4566" -H "x-amz-date: 20221219T221436Z" -H "x-amz-target: Kinesis_20131202.ListStreams" http://127.0.0.1:4500 -d '{}'`

**Expected behavior**

No error. (we could probably split on `,` and trim the whitespace.

**Comment by paulo-ferraz-oliveira** [comment]
@bentsku, good job posting the issue in this library. I was expecting you'd ask me to do it (over at LocalStack), thus the double post. Sorry for the confusion.

**Comment by bentsku** [comment]
No problem, I probably should have answered before posting here 😅
I was thinking about a fix as well, wanting to contribute, but Scala is unknown to me 😄
Splitting on `,` will have the issue on the first part of the string:
`"Authorization: AWS4-HMAC-SHA256 Credential=test/20221219/us-east-1/kinesis/aws4_request,SignedHeaders=content-type;host;x-amz-date;x-amz-target,Signature=ba9705e002b4f224d08c908606f0076a7f4f53bcc68315897764c587c7e5ffb5"`, between `AWS4-HMAC-SHA256` and `Credentials`. I don't know what the pattern would be in Scala 😕

**Comment by etspaceman** [comment]
Yeah it wouldn't be as easy as splitting on `,`. I think we could potentially do a `replace` command which adds a space after every comma, might be that easy.

**Comment by paulo-ferraz-oliveira** [comment]
Yes, my Scala is also limited 😄 and I was playing with an online playground. It's not just a question of splitting on `,`, for sure. My initial approach with be to work with Regex, but I'm not sure how much of a performance impact that would imply.

**Comment by etspaceman** [comment]
I've got a fix up, pretty easy change 😄

**Comment by etspaceman** [comment]
Fixed in #388

**Comment by paulo-ferraz-oliveira** [comment]
Thanks much.
