### ISSUE TITLE
[BUG] Kinesis Mock Server is increasing CPU to 100% on Localstack latest

### ISSUE THREAD

**Issue by rof20004** [etspaceman/kinesis-mock#669]
**Describe the bug**
When Kinesis is under high load with large records (e.g. 100 of records with ~256kB each) it slows down and eventually fail on out of memory.

**To Reproduce**

1. Start a localstack container:
```
docker container run \
  -d \
  --name localstack \
  --rm \
  -p 4566-4583:4566-4583 \
  -p 4510-4559:4510-4559 \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack" \
  -e SERVICES=s3,kinesis,iam,dynamodb,dynamodbstreams,lambda \
  --platform linux/amd64 \
  localstack/localstack
```

2. Create a kinesis stream:
```
aws kinesis create-stream \
  --stream-name captures-stream \
  --shard-count 1 \
  --endpoint-url http://localhost:4566 \
  --region sa-east-1
```

3. Send put-record 10 times on the shell, one after another with no waiting time:
```
aws kinesis put-record \   
    --stream-name captures-stream \
    --partition-key 1 \
    --data "Hi, how are you?" \
    --cli-binary-format raw-in-base64-out \
    --endpoint-url http://localhost:4566 \
    --region sa-east-1
```

**Expected behavior**
I expect to continue sending put-record data with no freeze

![Screenshot 2023-11-29 at 07 51 51](https://github.com/etspaceman/kinesis-mock/assets/1223682/f322333b-09ea-4337-b300-9f7ee52efa10)

**Comment by etspaceman** [comment]
I am not able to recreate this issue, both with localstack and kinesis-mock directly.

**Comment by rof20004** [comment]
@etspaceman I'm using MacOS M1 with Sonoma 14.1.1

I'm using default settings. When I did that command, docker stats shows this:

<img width="757" alt="image" src="https://github.com/etspaceman/kinesis-mock/assets/1223682/080e46a2-8e63-4dfd-9e68-41b1daee6bd7">

**Comment by etspaceman** [comment]
I'm doing the exact same thing and the CPU % is anywhere from 0.2% to 100+% and everything in between, but I don't see anything that persists or causes the behavior observed (freezing).

**Comment by stekycz** [comment]
@etspaceman I am giving 2 CPUs and 7GB of memory to my Docker Desktop and I was able to replicate the issue with both - localstack and Kinesis Mock Server directly. To replicate, you should turn on data persistency to JSON file(s).

**Comment by etspaceman** [comment]
> To replicate, you should turn on data persistency to JSON file(s).

I'm doing the exact commands that you've submitted in the issue which includes that. I am giving 2 CPUs and 8GB memory to my docker setup (via Rancher) as well.

**Comment by etspaceman** [comment]
I'd also like to note that [kinesis4cats](https://github.com/etspaceman/kinesis4cats/tree/main) leverages localstack in its integration tests, which will send upwards of 50+ records on each test invocation. We haven't seen this behavior in this environment.

**Comment by rof20004** [comment]
@etspaceman do you have Rosetta enabled on Docker Desktop?

<img width="847" alt="image" src="https://github.com/etspaceman/kinesis-mock/assets/1223682/f031e08b-4920-4b64-9422-b8a507713518">

**Comment by etspaceman** [comment]
I am not able to use Docker Desktop - I use Rancher as it is free 😄. This is using the QEMU emulator. So likely not. Is that something you can disable and test? Unfortunately I cannot leverage Docker Desktop on my machine.

**Comment by rof20004** [comment]
@etspaceman @stekycz I disabled Rosetta and it worked perfect. Maybe we have a compatibility issue with Rosetta.

**Comment by etspaceman** [comment]
That would make sense. Mind if I close this issue?

**Comment by rof20004** [comment]
@etspaceman No, thank you for the support :)

**Comment by etspaceman** [comment]
Of course! Good luck!
