### ISSUE TITLE
[BUG] Illegal Argument exception when using AWSCLI v2 with base64 encoded data

### ISSUE THREAD

**Issue by dfangl** [etspaceman/kinesis-mock#682]
**Describe the bug**
When trying to receive published, base64 encoded data using the AWS CLI v2, kinesis mock reports an `Illegal base64 character 22`

**To Reproduce**
1) Running kinesis mock with `docker run --rm -p 4566:4566 --name kinesis-mock -e KINESIS_MOCK_PLAIN_PORT=4566 ghcr.io/etspaceman/kinesis-mock:0.4.4`
2) Run the test script, and watch the logs:

```bash
#!/bin/bash
set -euxo pipefail
AWS=${AWS:-awslocal}
KINESIS_STREAM_NAME=test-stream

${AWS} kinesis create-stream --stream-name $KINESIS_STREAM_NAME --shard-count 1 --stream-mode-details StreamMode=PROVISIONED

base64_content=$(echo '{"test": "data"}' | base64)

${AWS} kinesis put-record \
  --stream-name $KINESIS_STREAM_NAME \
  --data  ${base64_content} --partition-key id

SHARD_ITERATOR=$(${AWS} kinesis get-shard-iterator --shard-id shardId-000000000000 --shard-iterator-type TRIM_HORIZON --stream-name $KINESIS_STREAM_NAME --query 'ShardIterator');

${AWS} kinesis get-records --shard-iterator $SHARD_ITERATOR
```

Using aws cli v2:
```
aws-cli/2.8.3 Python/3.9.11 Linux/6.6.6-arch1-1 exe/x86_64.arch prompt/off
```

The CLI documentation for the aws cli v2 specifies (https://awscli.amazonaws.com/v2/documentation/api/latest/reference/kinesis/put-record.html):

> The formatting style to be used for binary blobs. The default format is base64. The base64 format expects binary blobs to be provided as a base64 encoded string.

I confirmed that the payload sent to kinesis is indeed base64 encoded once.

Also, I validated the case against AWS.

**Expected behavior**
Records get returned properly.

**Error logs**
```
[error] kinesis.mock.KinesisMockService$ 2023-12-12T16:56:24.557165Z contextId=fa937ab2-8e90-46c1-a35a-081f9b30f185 Error servicing request: POST / from 172.17.0.1
java.lang.IllegalArgumentException: Illegal base64 character 22
  at oy.loa(/main.js:506:31)
  at mra(/main.js:507:249)
  at hqb(/main.js:3470:21)
  at {anonymous}()(/main.js:3320:72)
  at w.h(/main.js:2942:262)
  at z7(/main.js:4433:246)
  at e.Nk(/main.js:4461:328)
  at ZN.Nk(/main.js:1376:197)
  at {anonymous}()(/main.js:3605:53)
  at u.ra(/main.js:2942:45)
```
**Additional context**
This first occurred as a bug within LocalStack, but we verified it against `kinesis-mock` with the given instructions directly.

Happy to help with anything, however I would appreciate pointing me in the right direction, my scala is rather bad.

EDIT: `aws-mock` => `kinesis-mock`. Somehow messed this up :)

**Comment by etspaceman** [comment]
I'm a little confused on the use case here. Wouldn't this result in double base64 encoding? Typically when interacting with the aws cli, you just send the unencoded data.

**Comment by dfangl** [comment]
With aws cli V2, the default Mode (without `raw-in-base64-out`) it should take the base64 and not double encode it. I will double-check the wire format, but if I remember correctly it is not double base64 encoded.

**Comment by etspaceman** [comment]
Ah I see the item in the documentation now. I can take a look into this.

**Comment by etspaceman** [comment]
I think the issue with your script is here:

`SHARD_ITERATOR=$(${AWS} kinesis get-shard-iterator --shard-id shardId-000000000000 --shard-iterator-type TRIM_HORIZON --stream-name $KINESIS_STREAM_NAME --query 'ShardIterator');`

What happens is that the result is encapsulated in double-quotes. E.g. `"AAAAAAAAAAFKBrg2QSdJBHErnvUcZTJimAdal2SOXPJAZZ4U8lK1C2yqgf4Uio89mBPbYYUY6qX3/ug/cnn7YH0LLuZxyOFCh6hLtMj3YeO8a3O4mlMhM6riEOMpcIF/HZ4poJrs/qWd5w/vcFRu89hXcXriUJ8O9bJvIWm3VRhoy2GlKzwWW5HSnWlT60Dc3xZiKD5pgzY="`. kinesis-mock doesn't like the double quotes because it cannot parse it correctly. 

Without the double quotes, things work great on my end. Was able to retrieve the records.

**Comment by dfangl** [comment]
Ah thanks! Will confirm this tomorrow, when I get back to my machine.

Still, it works with this script on aws. While I agree that this is only a minimal issue, we try to be as accepting as aws in that regard. 

I can raise a quick PR which strips out the quotes from the shard iterator on the API side, if this is ok with you? Otherwise we can strip it out on the localstack side before it gets forwarded as well, if you prefer that.

Thanks for the quick confirmation and analysis!

**Comment by etspaceman** [comment]
> Still, it works with this script on aws. 

When you say this, do you mean on an actual AWS kinesis stream? Or against `aws-mock`? (As a side note, can you link me as to what `aws-mock` is?)

**Comment by dfangl** [comment]
I am so sorry, I mean kinesis-mock. It seems I had a brain freeze when typing this. I just meant I tested it against this project without going through localstack as well, to ensure we do nothing wrong while proxying.

Yes, i tested it against aws and it worked. However, I am not sure if the return value was without quotes, or it accepts them with quotes. I will check right away!

**Comment by etspaceman** [comment]
Cool, thanks. Yeah if AWS accepts it, kinesis-mock should too. The update would need to be made [here](https://github.com/etspaceman/kinesis-mock/blob/main/kinesis-mock/src/main/scala/kinesis/mock/models/ShardIterator.scala#L33). We'd also need a test for it.

**Comment by dfangl** [comment]
Just double checked against AWS to be sure:
It actually sends the shard iterator including the double quotes, and is fine with it. The body looks like this:
```
'body': b'{"ShardIterator": "\\"AAAAAAAAAAFyfvzLhrSct576P2qqlSiKkMj2x+2RW1T4ud3UeOURVmvU5hzkOWkUHdz6GXVWy9wUs/W41wOIe3we1M3mWfczfd8TvPkqvKosoDqzMxhjY6sqSImrRoM3q6+CjShyJ0PT3Q/0q1NsQHYjAJQhLhl/YgkEOqBbY1AHaXvb9viwvi4gv/+TwU7zHQ4+wHnWOSKOJcfmN0uN1Q7knSxPQbGbKvJ45h+R3vTCcXQgMXPDsQ==\\""}',
```
Including the escaped double quotes. Will try to get a quick PR open tomorrow!

**Comment by etspaceman** [comment]
Does the `getRecords` call succeed with that value passed as the ShardIterator?

**Comment by dfangl** [comment]
Yes, exactly.
